# Generated by Django 6.1.1 on 2026-09-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('TechDataAuto', 'Technical Data Sheet — Auto Fields'), ('SectionA', 'Pricing Section A — Raw Materials'), ('SectionB', 'Pricing Section B — Ancillary Parts'), ('SectionC', 'Pricing Section C — In-House Processing'), ('SectionD', 'Pricing Section D — Outsourced Processing'), ('SectionE', 'Pricing Section E — Packing & Shipment'), ('SectionF', 'Pricing Section F — Summary')], max_length=20)),
                ('expression', models.TextField(help_text='Restricted arithmetic expression — see simpleeval/expr-eval grammar.')),
                ('input_variables', models.JSONField(default=list, help_text='Variable names this expression may reference.')),
                ('output_unit', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FormulaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_expression', models.TextField()),
                ('new_expression', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='formulas.formuladefinition')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
