# Generated by Django 6.1.1 on 2026-09-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDataFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text="Only used when field_type='select' and not catalog-driven.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within its section — not evaluation order.')),
                ('is_core', models.BooleanField(default=False)),
                ('is_catalog_derived', models.BooleanField(default=False, help_text='Read-only, populated by a catalog lookup when its paired designation field changes (see PRICE_FIELD_SOURCE/lookupCatalogPrice in pulleyTechDataSchema.ts) rather than a FormulaDefinition. Renders read-only like an Auto field but has no `formula` — only ever True on backfilled core fields, never settable via the create API since it requires actual catalog-key wiring in code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_data_field', to='formulas.formuladefinition')),
            ],
            options={
                'ordering': ['section', 'order', 'key'],
            },
        ),
    ]
