# Generated by Django 6.1.1 on 2026-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_populate_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdatafielddefinition',
            name='fixed_value',
            field=models.CharField(blank=True, help_text="When set, every RFQ's Technical Data Sheet fills this value in automatically and shows it read-only (no input/dropdown). Must be one of `options` for a select field.", max_length=200),
        ),
    ]
