# Generated by Django 6.1.1 on 2026-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_techdatafield_fixed_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdatafielddefinition',
            name='options_source',
            field=models.CharField(blank=True, help_text='Reference catalog the options were imported from ("table::field"), so the Formulas page can show it again.', max_length=120),
        ),
    ]
