# Generated by Django 6.1.1 on 2026-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_remove_rfq_attachments_rfqattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='field_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-item Technical Data Sheet field type overrides, keyed by field key: {"bearing1Designation": {"fieldType": "select", "options": [...]}}. Fields not listed here use the global TechDataFieldDefinition. Only Controlling/Admin may change these (see validate_field_overrides).'),
        ),
    ]
