# Generated by Django 6.1.1 on 2026-09-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BearingCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=60, unique=True)),
                ('bore_mm', models.FloatField()),
                ('price_inr', models.FloatField()),
                ('price_eur', models.FloatField()),
                ('delivery_days', models.PositiveIntegerField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bore_mm', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='CostRateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Global', 'Global Parameters'), ('Material', 'Material Rates'), ('Labour', 'Machining & Labour Rates'), ('Logistics', 'Logistics & Packing Rates')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HousingCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_bearing', models.CharField(blank=True, max_length=60)),
                ('housing_designation', models.CharField(max_length=60)),
                ('price_inr', models.FloatField()),
                ('delivery_days', models.PositiveIntegerField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['housing_designation'],
            },
        ),
        migrations.CreateModel(
            name='LaggingCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lagging_type', models.CharField(max_length=60)),
                ('thickness_mm', models.FloatField()),
                ('price_inr_per_m2', models.FloatField()),
                ('delivery_days', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lagging_type', 'thickness_mm'],
            },
        ),
        migrations.CreateModel(
            name='LockingDeviceCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(db_column='model', max_length=60)),
                ('negotiated_rate_inr', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='RawForgingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.CharField(choices=[('shaft', 'Shaft'), ('shell', 'Shell')], max_length=10)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('sourcing', models.CharField(blank=True, choices=[('Outsourced', 'Outsourced'), ('Inhouse', 'In-house')], max_length=12)),
                ('size_band_label', models.CharField(help_text="e.g. 'Ø 80 - 180' or '>550 - 1000'", max_length=100)),
                ('plate_rate_inr_per_kg', models.FloatField(blank=True, null=True)),
                ('end_disc_rate_inr_per_kg', models.FloatField(blank=True, null=True)),
                ('is_active_default', models.BooleanField(default=False, help_text='The row Pricing Tool actually reads today.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SleeveCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_bearing', models.CharField(blank=True, max_length=60)),
                ('sleeve_code', models.CharField(max_length=60)),
                ('price_eur', models.FloatField()),
                ('price_inr', models.FloatField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sleeve_code'],
            },
        ),
    ]
