# Generated by Django 6.1.1 on 2026-09-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InHouseHourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_head', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=150)),
                ('cost_centre', models.CharField(blank=True, max_length=30)),
                ('activity_description', models.CharField(max_length=150)),
                ('mhr_rate', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'cost_head'],
            },
        ),
    ]
