# Generated by Django 6.1.1 on 2026-09-21 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_inhousehourrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('default_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=3)),
                ('tax_registration_label', models.CharField(blank=True, default='GSTIN', max_length=50)),
                ('default_tax_applicability', models.CharField(blank=True, max_length=200)),
                ('sla_days_operations_review', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_days_sourcing', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_days_controlling', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_days_approval', models.PositiveIntegerField(blank=True, null=True)),
                ('notify_on_stage_change', models.BooleanField(default=True)),
                ('notify_email_enabled', models.BooleanField(default=False)),
                ('quotation_header_text', models.TextField(blank=True)),
                ('quotation_footer_text', models.TextField(blank=True)),
                ('quotation_validity_days_default', models.PositiveIntegerField(blank=True, null=True)),
                ('terms_and_conditions_text', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
