# Generated by Django 6.1.1 on 2026-09-29 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_split_cost_rate_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaftForgingBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(help_text="e.g. '42CrMo4+QT'", max_length=100)),
                ('diameter', models.CharField(help_text="e.g. 'Ø 200 - 880'", max_length=100)),
                ('length', models.CharField(help_text="e.g. '2300 - 7300'", max_length=100)),
                ('sourcing', models.CharField(blank=True, choices=[('Outsourced', 'Outsourced'), ('Inhouse', 'In-house')], max_length=12)),
                ('as_forge_rate_inr_per_kg', models.FloatField(blank=True, help_text="Blank means 'As per RFQ'.", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShellForgingBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sourcing', models.CharField(blank=True, choices=[('Outsourced', 'Outsourced'), ('Inhouse', 'In-house')], max_length=12)),
                ('diameter_body', models.CharField(help_text="e.g. '300 - <=500'", max_length=100)),
                ('face_width_body', models.CharField(help_text="e.g. '800-1200'", max_length=100)),
                ('wall_thickness', models.CharField(blank=True, help_text="Body → sheet +x mm, e.g. '10-12'", max_length=100)),
                ('welded_in_plate_thickness', models.CharField(blank=True, help_text="e.g. '50-80'", max_length=100)),
                ('t_bottom_thickness', models.CharField(blank=True, help_text="e.g. '100-150'", max_length=100)),
                ('plate_rate_inr_per_kg', models.FloatField(blank=True, null=True)),
                ('end_disc_hub_rate_inr_per_kg', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='RawForgingRate',
        ),
    ]
