# Generated by Django 6.1.1 on 2026-09-29 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_replace_raw_forging_with_shaft_shell_bands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LagDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lagging_type', models.CharField(help_text="Lookup key, e.g. 'Rubber vulc. 12mm'", max_length=100, unique=True)),
                ('thickness_mm', models.FloatField()),
                ('price_inr_per_m2', models.FloatField()),
                ('delivery_days', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'lag data entries',
                'ordering': ['id'],
            },
        ),
    ]
