# Generated by Django 6.1.1 on 2026-09-29 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_lagdataentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LcdDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_size', models.CharField(help_text="e.g. 'NMTG N7036-100 × 150'", max_length=100, unique=True)),
                ('indicative_price', models.CharField(blank=True, help_text="Free text range, e.g. '₹25,000 – ₹35,000'", max_length=100)),
                ('negotiated_rate_inr', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LCD data entries',
                'ordering': ['id'],
            },
        ),
    ]
