# Generated by Django 6.1.1 on 2026-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_lcddataentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shaftforgingband',
            name='sourcing',
        ),
        migrations.AddField(
            model_name='shaftforgingband',
            name='rate_dia_410_lg_3900_inr_per_kg',
            field=models.FloatField(blank=True, help_text='Ø 410, lg 3900 (₹/kg)', null=True),
        ),
        migrations.AddField(
            model_name='shaftforgingband',
            name='rate_dia_420_800_lg_2000_inr_per_kg',
            field=models.FloatField(blank=True, help_text='Ø 420-800, lg 2000 (₹/kg)', null=True),
        ),
    ]
