# Generated by Django 6.1.1 on 2026-10-09 07:44

from django.db import migrations, models


def tidy_converted_numbers(apps, schema_editor):
    # The float -> text cast can leave '310.0'; store whole numbers as '310'.
    ShaftForgingBand = apps.get_model("reference", "ShaftForgingBand")
    for band in ShaftForgingBand.objects.exclude(as_forge_rate_inr_per_kg__isnull=True):
        value = band.as_forge_rate_inr_per_kg
        if value.endswith(".0"):
            band.as_forge_rate_inr_per_kg = value[:-2]
            band.save(update_fields=["as_forge_rate_inr_per_kg"])


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_shaft_band_rate_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaftforgingband',
            name='as_forge_rate_inr_per_kg',
            field=models.CharField(blank=True, help_text="e.g. 'Rs 175 - 225'. Blank means 'As per RFQ'.", max_length=100, null=True),
        ),
        migrations.RunPython(tidy_converted_numbers, migrations.RunPython.noop),
    ]
